# Workflow name
name: K8 EE build

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches:
      - master
    paths:
      - 'k8_ee/**'

  # Schedule workflow run at 00:00 on Sunday
  #schedule:
  #  - cron: '0 0 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call-deploy-workflow:
    uses:  amelcocloud/awx-ee/.github/workflows/deploy.yml@master
    with:
      EE_FOLDER_NAME: 'k8_ee'
      EE_IMAGE_TAG: 'latest'
      # github-actions_awx-ee IAM user
      AWS_ACCESS_KEY_ID: AKIAV5GGD5BGD5Y6BAHV
    secrets:
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
